---
- name: Manage AWS EC2 based on tags
  hosts: all
  gather_facts: yes
  become: yes

  roles:
    - { role: hostname, when: Managed | bool }
    - { role: service, when: Managed | bool }
    - { role: restart, when: Managed | bool }
